name: interviewmate-infra

services:
  mysql:
    image: mysql:8.0
    container_name: backend-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

    networks:
      - interviewmate-network

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 10s
      retries: 10
      start_period: 40s


  redis:
    image: redis:7.2
    container_name: backend-redis

    volumes:
      - redis-data:/data

    networks:
      - interviewmate-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 10
      start_period: 20s


  kafka:
    image: arindampal28/bitnami-kafka:latest
    container_name: backend-kafka

    environment:
      # KAFKA_CFG_NODE_ID: 1
      # KAFKA_CFG_PROCESS_ROLES: broker,controller
      # KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      # KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      # KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      # ALLOW_PLAINTEXT_LISTENER: "yes"
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LOG_DIRS=/bitnami/kafka/data
      - KAFKA_CLUSTER_ID=abcdefghijklmnopqrstuv

    volumes:
      - kafka-data:/bitnami/kafka

    networks:
      - interviewmate-network

    healthcheck:
      test: ["CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 10s
      retries: 10
      start_period: 30s


volumes:
  mysql-data:
  redis-data:
  kafka-data:

networks:
  interviewmate-network:
    external: true
