spring:
  application:
    name: user-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        "[show_sql]": false
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
server:
  port: ${USER_SERVICE_SERVER_PORT}

logging:
  level:
    root: INFO
    "[com.interviewmate.gateway]": INFO
    "[com.interviewmate.userservice]": INFO
    "[com.interviewmate.walletservice]": INFO
    "[com.interviewmate.transactionservice]": INFO
    "[org.springframework]": INFO
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[org.springframework.cache]": DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: logs/interviewmate-app.log

  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 30

jwt:
  secret: ${JWT_SECRET}
