
services:
  interview-service:
    image: arindampal28/interviewmate-interview-service:latest
    container_name: backend-interview-service
    env_file:
      - ../../.env
    networks:
      - interviewmate-network

    depends_on:
      kafka:
        condition: service_healthy
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8086/actuator/health || exit 1"]
      interval: 15s
      retries: 10
      start_period: 40s

    restart: always

networks:
  interviewmate-network:
    external: true
