
services:
  config-server:
    image: arindampal28/interviewmate-config-server:latest
    container_name: backend-config-server
    expose:
      - "8888" 
    env_file: 
      - ../.env

    networks:
      - interviewmate-network

    volumes:
      - config-logs:/app/logs

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  interviewmate-network:
    external: true

volumes:
  config-logs:
