#application-dev.properties

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: judge-worker-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        "[spring.json.trusted.packages]": "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

coding:
    judge0:
      baseUrl: ${JUDGE0_BASE_URL:http://localhost:2358}
      pollIntervalMs: ${JUDGE0_POLL_INTERVAL_MS:500}
      maxPollAttempts: ${JUDGE0_MAX_POLL_ATTEMPTS:40}
      connectTimeoutMs: ${JUDGE0_CONNECT_TIMEOUT_MS:2000}
      readTimeoutMs: ${JUDGE0_READ_TIMEOUT_MS:10000}  