
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resume_db
    username: arindam
    password: Ami10002@00125a
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

python:
  api:
    url: https://resumeservice.onrender.com/resumeanalyzer/api/v1
