
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resume_db
    username: arindam
    password: Ami10002@00125a
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

python:
  api:
    url: https://resumeservice.onrender.com/resumeanalyzer/api/v1

# -------------------
# Cloudinary (shared)
# -------------------
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# -------------------
# JPA (shared)
# -------------------
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        "[show_sql]": false
    hibernate:
      ddl-auto: update
# -------------------
# Cache (shared)
# -------------------
  cache:
    type: redis
    redis:
      time-to-live: 1h


# -------------------
# Logging (shared)
# -------------------
logging:
  level:
    root: INFO
    "[com.interviewmate.resumeservice]": INFO
    "[org.springframework]": INFO
    "[org.springframework.cache]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
