spring:
  datasource:
    url: ${RESUME_SPRING_DATASOURCE_URL}
    username: ${RESUME_SPRING_DATASOURCE_USERNAME}
    password: ${RESUME_SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

  kafka:
    producer:
      bootstrap-servers: ${SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

python:
  api:
    url: ${PYTHON_API_URL}
server:
  port: ${RESUME_SERVICE_SERVER_PORT}

  
# -------------------
# Cloudinary (shared)
# -------------------
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# -------------------
# Cache (shared)
# -------------------
  cache:
    type: redis
    redis:
      time-to-live: 1h
# -------------------
# JPA (shared)
# -------------------
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        "[show_sql]": false
    hibernate:
      ddl-auto: update

# -------------------
# Logging (shared)
# -------------------
logging:
  level:
    root: INFO
    "[com.interviewmate.resumeservice]": INFO
    "[org.springframework]": INFO
    "[org.springframework.cache]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
