server:
  port: ${CONFIG_SERVER_PORT:8888}
  shutdown: graceful
  forward-headers-strategy: framework

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          default-label: ${CONFIG_GIT_BRANCH:main}
          clone-on-start: true
          force-pull: true
          timeout: 15
          skip-ssl-validation: false
          delete-untracked-branches: true
          search-paths:
            - config
            - services
          username: ${CONFIG_GIT_USERNAME}
          password: ${CONFIG_GIT_PAT}

        encrypt:
          enabled: true

  security:
    user:
      name: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,refresh"
  endpoint:
    health:
      show-details: when_authorized


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    root: INFO
    '[org.springframework.cloud.config]': INFO
    '[com.interviewmate.configserver]': INFO

  file:
    name: /app/logs/config-server.log

  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 5GB

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"


