
services:
  coding-service:
    image: arindampal28/interviewmate-coding-service:latest
    container_name: backend-coding-service
    env_file:
      - ../../.env

    networks:
      - interviewmate-network

    depends_on:
       kafka:
        condition: service_healthy
       eureka-server:
        condition: service_started
       config-server:
        condition: service_started
      
        

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8085/actuator/health || exit 1"]
      interval: 10s
      retries: 10
      start_period: 40s

    restart: always

networks:
  interviewmate-network:
    external: true
