spring:
  application:
    name: notification-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  
  config:
    import: "configserver:http://config-server:8888"

  cloud:
    config:
      fail-fast: true
      username: ${CONFIG_SERVER_USERNAME:devconfig}
      password: ${CONFIG_SERVER_PASSWORD:devconfig}
      retry:
        max-attempts: 10
        initial-interval: 2000
        max-interval: 15000
        multiplier: 1.5


# -------------------
# Logging (shared)
# -------------------
logging:
  level:
    root: INFO
    "[com.interviewmate.gateway]": INFO
    "[org.springframework]": INFO
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[org.springframework.kafka.listener]": DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: logs/interviewmate-app.log

  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 30
